package Ryce.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;

public class Images_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("import { useState, useEffect } from 'react';");
    tgs.newLine();
    tgs.append("import Photo from './Photo';");
    tgs.newLine();
    tgs.append("import '../styles/combined.css'");
    tgs.newLine();
    tgs.newLine();

    tgs.append("function Photos() {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("const [photos, setPhotos] = useState([]);");
    tgs.newLine();
    tgs.indent();
    tgs.append("const [currentPage, setCurrentPage] = useState(1);");
    tgs.newLine();
    tgs.indent();
    tgs.append("const [pagination, setPagination] = useState({});");
    tgs.newLine();
    tgs.indent();
    // replace default sort config and correct
    tgs.append("const [currentSort, setCurrentSort] = useState(");
    tgs.newLine();
    tgs.newLine();
    tgs.indent();
    tgs.append("useEffect(() => {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("const getPhotos = async () => {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    // Handle api stuff
    tgs.append("const res = await fetch(config.base_api + 'images/?page=' + currentPage + \"&limit=\" + config.images_per_page + \"&sort=\" + currentSort);");
    tgs.newLine();
    tgs.indent();
    tgs.append("const data = await res.json();");
    tgs.newLine();
    tgs.indent();
    tgs.append("setPhotos(data.photos);");
    tgs.newLine();
    tgs.indent();
    tgs.append("setPagination(data.pagination);");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("};");
    tgs.newLine();
    tgs.indent();
    tgs.append("getPhotos();");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("}, [currentPage, currentSort]);");
    tgs.newLine();
    tgs.newLine();

    tgs.indent();
    tgs.append("const handleNextPage = () => {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("if (currentPage < pagination.totalPages) {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("setCurrentPage(currentPage + 1);");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("};");
    tgs.newLine();
    tgs.newLine();

    tgs.indent();
    tgs.append("const handlePrevPage = () => {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("if (currentPage > 1) {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("setCurrentPage(currentPage - 1);");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("}");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("};");
    tgs.newLine();
    tgs.newLine();

    tgs.indent();
    tgs.append("const handleSortChange = (event) => {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("const newSort = event.target.value;");
    tgs.newLine();
    tgs.indent();
    tgs.append("setCurrentSort(newSort);");
    tgs.newLine();
    tgs.indent();
    tgs.append("setCurrentPage(1);");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("};");
    tgs.newLine();
    tgs.newLine();

    tgs.indent();
    tgs.append("const getSortDisplayName = (sortValue) => {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("const displayNames = {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("'newest_asc': 'Oldest First',");
    tgs.newLine();
    tgs.indent();
    tgs.append("'newest_dsc': 'Newest First',");
    tgs.newLine();
    tgs.indent();
    tgs.append("'likes_asc': 'Least Likes',");
    tgs.newLine();
    tgs.indent();
    tgs.append("'likes_dsc': 'Most Likes',");
    tgs.newLine();
    tgs.indent();
    tgs.append("'title_asc': 'Title A-Z',");
    tgs.newLine();
    tgs.indent();
    tgs.append("'title_dsc': 'Title Z-A'");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("};");
    tgs.newLine();
    tgs.indent();
    tgs.append("return displayNames[sortValue] || sortValue;");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("};");
    tgs.newLine();
    tgs.newLine();

    tgs.append("return (");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
  }
}
