package Ryce.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Menu_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("import { useContext, useEffect, useState } from \"react\";");
    tgs.newLine();
    tgs.append("import { UserContext } from \"../userContexts\";");
    tgs.newLine();
    tgs.append("import { Link, useLocation } from \"react-router-dom\";");
    tgs.newLine();
    tgs.append("import { User, Image, Plus } from 'feather-icons-react';");
    tgs.append("import { FaPaintBrush } from \"react-icons/fa\";");
    tgs.newLine();
    tgs.append("import UserDisplay from \"./UserDisplay\";");
    tgs.newLine();
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$SqYo), 0x5f82ea2efcb96887L)) {
      tgs.append("import \"HeaderTopbar.css\";");
      tgs.newLine();
      tgs.newLine();
    } else if (SEnumOperations.isMember(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$SqYo), 0x5f82ea2efcb9688aL)) {
      tgs.append("import \"HeaderSidebar.css\";");
      tgs.newLine();
      tgs.newLine();
    }

    ctx.getBuffer().area().increaseIndent();
    tgs.append("function Header() {");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("const { user } = useContext(UserContext);");
    tgs.newLine();
    tgs.newLine();

    tgs.indent();
    tgs.append("return (");
    tgs.newLine();

    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$SqYo), 0x5f82ea2efcb96887L)) {
      tgs.append("<div className=\"navbar navbar-expand-lg navbar-dark bg-dark px-3\">");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      tgs.append("<div>");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.title_option$Cz$y) != null)) {
        tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.title_option$Cz$y));
        tgs.newLine();
      }
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("</div>");
      tgs.newLine();

      tgs.indent();
      tgs.append("<div className=\"collapse navbar-collapse\" id=\"navbarNav\">");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      tgs.append("<ul className=\"navbar-nav me-auto align-items-center\">");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.options$ZNrU) != null)) {
        tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.options$ZNrU));
        tgs.newLine();
        tgs.indent();
      }
      tgs.newLine();
      tgs.indent();
      tgs.append("{user ? (");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      tgs.append("<>");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.options_IsSet$2m8f) != null)) {
        tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.options_IsSet$2m8f));
        tgs.newLine();
      }
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("</>");
      tgs.newLine();
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append(") : (");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      tgs.append("<>");
      tgs.newLine();
      ctx.getBuffer().area().increaseIndent();
      tgs.indent();
      if ((SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.options_NotSet$2mng) != null)) {
        tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.options_NotSet$2mng));
        tgs.newLine();
      }
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("</>");
      tgs.newLine();
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append(")}");
      tgs.newLine();
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("</ul>");
      tgs.newLine();
      if (SPropertyOperations.getBoolean(ctx.getPrimaryInput(), PROPS.user_display$BPl$)) {
        tgs.indent();
        tgs.append("<UserDisplay />");
        tgs.newLine();
      }
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("</div>");
      tgs.newLine();
      ctx.getBuffer().area().decreaseIndent();
      tgs.indent();
      tgs.append("</div>");
      tgs.newLine();
    } else if (SEnumOperations.isMember(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.type$SqYo), 0x5f82ea2efcb9688aL)) {
    }

    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append(");");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.append("}");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$SqYo = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x605f898c118a05aeL, "type");
    /*package*/ static final SProperty user_display$BPl$ = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x762ed1772a479779L, "user_display");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink title_option$Cz$y = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x605f898c1134850dL, "title_option");
    /*package*/ static final SContainmentLink options$ZNrU = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x5f82ea2efca8b125L, "options");
    /*package*/ static final SContainmentLink options_IsSet$2m8f = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x4b61efe7ede292efL, "options_IsSet");
    /*package*/ static final SContainmentLink options_NotSet$2mng = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x4b61efe7ede292f0L, "options_NotSet");
  }
}
