package Ryce.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class Style_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode style : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.CSSproperties$9YR))) {
      tgs.append(SPropertyOperations.getString(style, PROPS.name$hrv));
      tgs.append(":");
      tgs.append(SPropertyOperations.getString(style, PROPS.value$m_P));
      tgs.append(";");
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$hrv = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b13bL, 0x5f82ea2efca8b14dL, "name");
    /*package*/ static final SProperty value$m_P = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b13bL, 0x5f82ea2efca8b14eL, "value");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink CSSproperties$9YR = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b139L, 0x5f82ea2efca8b143L, "CSSproperties");
  }
}
