package Ryce.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class TitleMenuOption_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    for (SNode option : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.option$u6cp))) {
      if (SEnumOperations.isMember(SPropertyOperations.getEnum(SNodeOperations.cast(SNodeOperations.getParent(ctx.getPrimaryInput()), CONCEPTS.Menu$SI), PROPS.type$SqYo), 0x5f82ea2efcb96887L)) {
        tgs.append("<Link className=\"navbar-brand d-flex align-items-center\" to=\"");
        tgs.append(SPropertyOperations.getString(option, PROPS.url$4eWq));
        tgs.append("\">");
        tgs.newLine();
        ctx.getBuffer().area().increaseIndent();
        tgs.indent();
        if ((SLinkOperations.getTarget(option, LINKS.icon$KTkR) != null)) {
          tgs.append("<");
          tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(option, LINKS.icon$KTkR), PROPS.iconName$he9p));
          tgs.append(" size={");
          tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(option, LINKS.icon$KTkR), PROPS.size$tFxB));
          tgs.append("} className=\"me-2\" style={{ color: 'rgb(0, 174, 3)' }}/>");
          tgs.newLine();
          tgs.indent();
        }
        tgs.append("<span className=\"icon-text\">");
        tgs.append(SPropertyOperations.getString(option, PROPS.text$4fbr));
        tgs.append("</span>");
        tgs.newLine();
        ctx.getBuffer().area().decreaseIndent();
        tgs.indent();
        tgs.append("</Link>");
        if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.option$u6cp)).last() != option) {
          tgs.newLine();
        }
        tgs.indent();
      } else if (SEnumOperations.isMember(SPropertyOperations.getEnum(SNodeOperations.cast(SNodeOperations.getParent(ctx.getPrimaryInput()), CONCEPTS.Menu$SI), PROPS.type$SqYo), 0x5f82ea2efcb9688aL)) {
        tgs.append("<Link className=\"brand-link\" to=\"");
        tgs.append(SPropertyOperations.getString(option, PROPS.url$4eWq));
        tgs.append("\">");
        tgs.newLine();
        ctx.getBuffer().area().increaseIndent();
        tgs.indent();
        if ((SLinkOperations.getTarget(option, LINKS.icon$KTkR) != null)) {
          tgs.append("<");
          tgs.append(SPropertyOperations.getString(SLinkOperations.getTarget(option, LINKS.icon$KTkR), PROPS.iconName$he9p));
          tgs.append(" className=\"brand-icon\" />");
          tgs.newLine();
          tgs.indent();
        }
        tgs.append("<span className=\"brand-text\">");
        tgs.append(SPropertyOperations.getString(option, PROPS.text$4fbr));
        tgs.append("</span>");
        tgs.newLine();
        ctx.getBuffer().area().decreaseIndent();
        tgs.indent();
        tgs.append("</Link>");
        if (ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.option$u6cp)).last() != option) {
          tgs.newLine();
        }
        tgs.indent();
      }
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Menu$SI = MetaAdapterFactory.getConcept(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, "Ryce.structure.Menu");
  }

  private static final class PROPS {
    /*package*/ static final SProperty type$SqYo = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L, 0x605f898c118a05aeL, "type");
    /*package*/ static final SProperty url$4eWq = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb389d0L, 0x5f82ea2efcb389d2L, "url");
    /*package*/ static final SProperty iconName$he9p = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x39c93bd42dd4d43cL, 0x39c93bd42dd4d43dL, "iconName");
    /*package*/ static final SProperty size$tFxB = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x39c93bd42dd4d43cL, 0x503665969865d1dcL, "size");
    /*package*/ static final SProperty text$4fbr = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb389d0L, 0x5f82ea2efcb389d3L, "text");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink icon$KTkR = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb389d0L, 0x39c93bd42dd4d43eL, "icon");
    /*package*/ static final SContainmentLink option$u6cp = MetaAdapterFactory.getContainmentLink(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x605f898c115e3b2dL, 0x605f898c115e3b2eL, "option");
  }
}
