package Ryce.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SEnumOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class UserDisplay_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    if (SEnumOperations.isMember(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.display_type$qIzj), 0x40381b488ec39513L)) {
      tgs.append("<div>");
      tgs.newLine();
    } else if (SEnumOperations.isMember(SPropertyOperations.getEnum(ctx.getPrimaryInput(), PROPS.display_type$qIzj), 0x40381b488ec39514L)) {
      tgs.append("<div className=\"sidebar-user\">");
      tgs.newLine();
    }
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<UserDisplay />");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</div>");
  }

  private static final class PROPS {
    /*package*/ static final SProperty display_type$qIzj = MetaAdapterFactory.getProperty(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x40381b488ec39511L, 0x40381b488ec39517L, "display_type");
  }
}
