package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Api;
  private ConceptPresentation props_BaseUrl;
  private ConceptPresentation props_ClickActions;
  private ConceptPresentation props_ClickEndpoint;
  private ConceptPresentation props_Component;
  private ConceptPresentation props_Components;
  private ConceptPresentation props_Content;
  private ConceptPresentation props_ContentSource;
  private ConceptPresentation props_Contents;
  private ConceptPresentation props_Dislike;
  private ConceptPresentation props_DislikeClickAction;
  private ConceptPresentation props_Enable;
  private ConceptPresentation props_EnableComponents;
  private ConceptPresentation props_Endpoint;
  private ConceptPresentation props_Endpoints;
  private ConceptPresentation props_Favorite;
  private ConceptPresentation props_FavoriteClickAction;
  private ConceptPresentation props_Footer;
  private ConceptPresentation props_ForEach;
  private ConceptPresentation props_Icon;
  private ConceptPresentation props_ImageLayout;
  private ConceptPresentation props_ImageLink;
  private ConceptPresentation props_Images;
  private ConceptPresentation props_ItemsPerPage;
  private ConceptPresentation props_Like;
  private ConceptPresentation props_LikeClickAction;
  private ConceptPresentation props_LoadAction;
  private ConceptPresentation props_LoadElement;
  private ConceptPresentation props_Menu;
  private ConceptPresentation props_MenuOption;
  private ConceptPresentation props_MenuOptionElement;
  private ConceptPresentation props_MenuOptionIsNotSet;
  private ConceptPresentation props_MenuOptionIsSet;
  private ConceptPresentation props_MenuType;
  private ConceptPresentation props_Parameter;
  private ConceptPresentation props_Payload;
  private ConceptPresentation props_PayloadElement;
  private ConceptPresentation props_Position;
  private ConceptPresentation props_Set;
  private ConceptPresentation props_Sorting;
  private ConceptPresentation props_Style;
  private ConceptPresentation props_StyleElement;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Api:
        if (props_Api == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Api = cpb.create();
        }
        return props_Api;
      case LanguageConceptSwitch.BaseUrl:
        if (props_BaseUrl == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("BaseUrl");
          props_BaseUrl = cpb.create();
        }
        return props_BaseUrl;
      case LanguageConceptSwitch.ClickActions:
        if (props_ClickActions == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ClickActions");
          props_ClickActions = cpb.create();
        }
        return props_ClickActions;
      case LanguageConceptSwitch.ClickEndpoint:
        if (props_ClickEndpoint == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ClickEndpoint");
          props_ClickEndpoint = cpb.create();
        }
        return props_ClickEndpoint;
      case LanguageConceptSwitch.Component:
        if (props_Component == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Component = cpb.create();
        }
        return props_Component;
      case LanguageConceptSwitch.Components:
        if (props_Components == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Components = cpb.create();
        }
        return props_Components;
      case LanguageConceptSwitch.Content:
        if (props_Content == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Content");
          props_Content = cpb.create();
        }
        return props_Content;
      case LanguageConceptSwitch.ContentSource:
        if (props_ContentSource == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ContentSource");
          props_ContentSource = cpb.create();
        }
        return props_ContentSource;
      case LanguageConceptSwitch.Contents:
        if (props_Contents == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Contents");
          props_Contents = cpb.create();
        }
        return props_Contents;
      case LanguageConceptSwitch.Dislike:
        if (props_Dislike == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Dislike");
          props_Dislike = cpb.create();
        }
        return props_Dislike;
      case LanguageConceptSwitch.DislikeClickAction:
        if (props_DislikeClickAction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("DislikeClickAction");
          props_DislikeClickAction = cpb.create();
        }
        return props_DislikeClickAction;
      case LanguageConceptSwitch.Enable:
        if (props_Enable == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Enable");
          props_Enable = cpb.create();
        }
        return props_Enable;
      case LanguageConceptSwitch.EnableComponents:
        if (props_EnableComponents == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("EnableComponents");
          props_EnableComponents = cpb.create();
        }
        return props_EnableComponents;
      case LanguageConceptSwitch.Endpoint:
        if (props_Endpoint == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Endpoint = cpb.create();
        }
        return props_Endpoint;
      case LanguageConceptSwitch.Endpoints:
        if (props_Endpoints == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Endpoints");
          props_Endpoints = cpb.create();
        }
        return props_Endpoints;
      case LanguageConceptSwitch.Favorite:
        if (props_Favorite == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Favorite");
          props_Favorite = cpb.create();
        }
        return props_Favorite;
      case LanguageConceptSwitch.FavoriteClickAction:
        if (props_FavoriteClickAction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("FavoriteClickAction");
          props_FavoriteClickAction = cpb.create();
        }
        return props_FavoriteClickAction;
      case LanguageConceptSwitch.Footer:
        if (props_Footer == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Footer = cpb.create();
        }
        return props_Footer;
      case LanguageConceptSwitch.ForEach:
        if (props_ForEach == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ForEach");
          props_ForEach = cpb.create();
        }
        return props_ForEach;
      case LanguageConceptSwitch.Icon:
        if (props_Icon == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Icon");
          props_Icon = cpb.create();
        }
        return props_Icon;
      case LanguageConceptSwitch.ImageLayout:
        if (props_ImageLayout == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ImageLayout");
          props_ImageLayout = cpb.create();
        }
        return props_ImageLayout;
      case LanguageConceptSwitch.ImageLink:
        if (props_ImageLink == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ImageLink");
          props_ImageLink = cpb.create();
        }
        return props_ImageLink;
      case LanguageConceptSwitch.Images:
        if (props_Images == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Images = cpb.create();
        }
        return props_Images;
      case LanguageConceptSwitch.ItemsPerPage:
        if (props_ItemsPerPage == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("ItemsPerPage");
          props_ItemsPerPage = cpb.create();
        }
        return props_ItemsPerPage;
      case LanguageConceptSwitch.Like:
        if (props_Like == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Like");
          props_Like = cpb.create();
        }
        return props_Like;
      case LanguageConceptSwitch.LikeClickAction:
        if (props_LikeClickAction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("LikeClickAction");
          props_LikeClickAction = cpb.create();
        }
        return props_LikeClickAction;
      case LanguageConceptSwitch.LoadAction:
        if (props_LoadAction == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("LoadAction");
          props_LoadAction = cpb.create();
        }
        return props_LoadAction;
      case LanguageConceptSwitch.LoadElement:
        if (props_LoadElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("LoadElement");
          props_LoadElement = cpb.create();
        }
        return props_LoadElement;
      case LanguageConceptSwitch.Menu:
        if (props_Menu == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Menu = cpb.create();
        }
        return props_Menu;
      case LanguageConceptSwitch.MenuOption:
        if (props_MenuOption == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MenuOption");
          props_MenuOption = cpb.create();
        }
        return props_MenuOption;
      case LanguageConceptSwitch.MenuOptionElement:
        if (props_MenuOptionElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_MenuOptionElement = cpb.create();
        }
        return props_MenuOptionElement;
      case LanguageConceptSwitch.MenuOptionIsNotSet:
        if (props_MenuOptionIsNotSet == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MenuOptionIsNotSet");
          props_MenuOptionIsNotSet = cpb.create();
        }
        return props_MenuOptionIsNotSet;
      case LanguageConceptSwitch.MenuOptionIsSet:
        if (props_MenuOptionIsSet == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MenuOptionIsSet");
          props_MenuOptionIsSet = cpb.create();
        }
        return props_MenuOptionIsSet;
      case LanguageConceptSwitch.MenuType:
        if (props_MenuType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MenuType");
          props_MenuType = cpb.create();
        }
        return props_MenuType;
      case LanguageConceptSwitch.Parameter:
        if (props_Parameter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Parameter");
          props_Parameter = cpb.create();
        }
        return props_Parameter;
      case LanguageConceptSwitch.Payload:
        if (props_Payload == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Payload");
          props_Payload = cpb.create();
        }
        return props_Payload;
      case LanguageConceptSwitch.PayloadElement:
        if (props_PayloadElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("PayloadElement");
          props_PayloadElement = cpb.create();
        }
        return props_PayloadElement;
      case LanguageConceptSwitch.Position:
        if (props_Position == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Position");
          props_Position = cpb.create();
        }
        return props_Position;
      case LanguageConceptSwitch.Set:
        if (props_Set == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Set");
          props_Set = cpb.create();
        }
        return props_Set;
      case LanguageConceptSwitch.Sorting:
        if (props_Sorting == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Sorting");
          props_Sorting = cpb.create();
        }
        return props_Sorting;
      case LanguageConceptSwitch.Style:
        if (props_Style == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Style");
          props_Style = cpb.create();
        }
        return props_Style;
      case LanguageConceptSwitch.StyleElement:
        if (props_StyleElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("StyleElement");
          props_StyleElement = cpb.create();
        }
        return props_StyleElement;
    }
    return null;
  }
}
