package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Api;
  private ConceptPresentation props_BaseUrl;
  private ConceptPresentation props_Endpoint;
  private ConceptPresentation props_Endpoints;
  private ConceptPresentation props_Menu;
  private ConceptPresentation props_MenuOption;
  private ConceptPresentation props_MenuOptionElement;
  private ConceptPresentation props_MenuType;
  private ConceptPresentation props_Parameter;
  private ConceptPresentation props_Set;
  private ConceptPresentation props_Style;
  private ConceptPresentation props_StyleElement;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Api:
        if (props_Api == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Api = cpb.create();
        }
        return props_Api;
      case LanguageConceptSwitch.BaseUrl:
        if (props_BaseUrl == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("BaseUrl");
          props_BaseUrl = cpb.create();
        }
        return props_BaseUrl;
      case LanguageConceptSwitch.Endpoint:
        if (props_Endpoint == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Endpoint");
          props_Endpoint = cpb.create();
        }
        return props_Endpoint;
      case LanguageConceptSwitch.Endpoints:
        if (props_Endpoints == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Endpoints");
          props_Endpoints = cpb.create();
        }
        return props_Endpoints;
      case LanguageConceptSwitch.Menu:
        if (props_Menu == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Menu = cpb.create();
        }
        return props_Menu;
      case LanguageConceptSwitch.MenuOption:
        if (props_MenuOption == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MenuOption");
          props_MenuOption = cpb.create();
        }
        return props_MenuOption;
      case LanguageConceptSwitch.MenuOptionElement:
        if (props_MenuOptionElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_MenuOptionElement = cpb.create();
        }
        return props_MenuOptionElement;
      case LanguageConceptSwitch.MenuType:
        if (props_MenuType == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("MenuType");
          props_MenuType = cpb.create();
        }
        return props_MenuType;
      case LanguageConceptSwitch.Parameter:
        if (props_Parameter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Parameter");
          props_Parameter = cpb.create();
        }
        return props_Parameter;
      case LanguageConceptSwitch.Set:
        if (props_Set == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Set");
          props_Set = cpb.create();
        }
        return props_Set;
      case LanguageConceptSwitch.Style:
        if (props_Style == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Style");
          props_Style = cpb.create();
        }
        return props_Style;
      case LanguageConceptSwitch.StyleElement:
        if (props_StyleElement == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("StyleElement");
          props_StyleElement = cpb.create();
        }
        return props_StyleElement;
    }
    return null;
  }
}
