package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_HttpMethod extends EnumerationDescriptorBase {

  public EnumerationDescriptor_HttpMethod() {
    super(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5cffed4b43879ad1L, "HttpMethod", "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6701335678061877969");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_GET_0 = new EnumerationDescriptor.MemberDescriptor("GET", "GET", 0x5cffed4b43879ad3L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6701335678061877971");
  private final EnumerationDescriptor.MemberDescriptor myMember_POST_0 = new EnumerationDescriptor.MemberDescriptor("POST", "POST", 0x5cffed4b43879ad2L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6701335678061877970");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5cffed4b43879ad1L, 0x5cffed4b43879ad3L, 0x5cffed4b43879ad2L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_GET_0, myMember_POST_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "GET":
        return myMember_GET_0;
      case "POST":
        return myMember_POST_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
