package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ComponentEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ComponentEnum() {
    super(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x39c93bd42dd7ce5fL, "ComponentEnum", "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4163925112968957535");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Menu_0 = new EnumerationDescriptor.MemberDescriptor("Menu", "Menu", 0x39c93bd42dd7ce60L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4163925112968957536");
  private final EnumerationDescriptor.MemberDescriptor myMember_Api_0 = new EnumerationDescriptor.MemberDescriptor("Api", "Api", 0x39c93bd42dd7ce62L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4163925112968957538");
  private final EnumerationDescriptor.MemberDescriptor myMember_ImageDisplay_0 = new EnumerationDescriptor.MemberDescriptor("ImageDisplay", "ImageDisplay", 0x39c93bd42dd7ce64L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4163925112968957540");
  private final EnumerationDescriptor.MemberDescriptor myMember_Style_0 = new EnumerationDescriptor.MemberDescriptor("Style", "Style", 0x39c93bd42dd7ce66L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4163925112968957542");
  private final EnumerationDescriptor.MemberDescriptor myMember_Footer_0 = new EnumerationDescriptor.MemberDescriptor("Footer", "Footer", 0x39c93bd42dd7ce68L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4163925112968957544");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x39c93bd42dd7ce5fL, 0x39c93bd42dd7ce60L, 0x39c93bd42dd7ce62L, 0x39c93bd42dd7ce64L, 0x39c93bd42dd7ce66L, 0x39c93bd42dd7ce68L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_Menu_0, myMember_Api_0, myMember_ImageDisplay_0, myMember_Style_0, myMember_Footer_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Menu":
        return myMember_Menu_0;
      case "Api":
        return myMember_Api_0;
      case "ImageDisplay":
        return myMember_ImageDisplay_0;
      case "Style":
        return myMember_Style_0;
      case "Footer":
        return myMember_Footer_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
