package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Alighment extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Alighment() {
    super(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x7f5e51ed8fb0ca8aL, "Alighment", "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9177863171387476618");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_vertical_0 = new EnumerationDescriptor.MemberDescriptor("vertical", "vertical", 0x7f5e51ed8fb0ca8bL, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9177863171387476619");
  private final EnumerationDescriptor.MemberDescriptor myMember_horizontal_0 = new EnumerationDescriptor.MemberDescriptor("horizontal", "horizontal", 0x7f5e51ed8fb0ca8cL, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9177863171387476620");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x7f5e51ed8fb0ca8aL, 0x7f5e51ed8fb0ca8bL, 0x7f5e51ed8fb0ca8cL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_vertical_0, myMember_horizontal_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "vertical":
        return myMember_vertical_0;
      case "horizontal":
        return myMember_horizontal_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
