package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_MenuTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_MenuTypes() {
    super(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb96886L, "MenuTypes", "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668104943750");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_topbar_0 = new EnumerationDescriptor.MemberDescriptor("topbar", "topbar", 0x5f82ea2efcb96887L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668104943751");
  private final EnumerationDescriptor.MemberDescriptor myMember_dropdown_0 = new EnumerationDescriptor.MemberDescriptor("dropdown", "dropdown", 0x5f82ea2efcb96889L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668104943753");
  private final EnumerationDescriptor.MemberDescriptor myMember_sidebar_0 = new EnumerationDescriptor.MemberDescriptor("sidebar", "sidebar", 0x5f82ea2efcb9688aL, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668104943754");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb96886L, 0x5f82ea2efcb96887L, 0x5f82ea2efcb96889L, 0x5f82ea2efcb9688aL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_topbar_0, myMember_dropdown_0, myMember_sidebar_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "topbar":
        return myMember_topbar_0;
      case "dropdown":
        return myMember_dropdown_0;
      case "sidebar":
        return myMember_sidebar_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
