package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_UserDisplayTypes extends EnumerationDescriptorBase {

  public EnumerationDescriptor_UserDisplayTypes() {
    super(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x40381b488ec39512L, "UserDisplayTypes", "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4627478615569962258");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_standard_0 = new EnumerationDescriptor.MemberDescriptor("standard", "standard", 0x40381b488ec39513L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4627478615569962259");
  private final EnumerationDescriptor.MemberDescriptor myMember_dropdown_0 = new EnumerationDescriptor.MemberDescriptor("dropdown", "dropdown", 0x40381b488ec39514L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/4627478615569962260");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x40381b488ec39512L, 0x40381b488ec39513L, 0x40381b488ec39514L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_standard_0, myMember_dropdown_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "standard":
        return myMember_standard_0;
      case "dropdown":
        return myMember_dropdown_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
