package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_SortingOptions extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SortingOptions() {
    super(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x7f63219c035cbddfL, "SortingOptions", "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9179217419466227167");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_newest_first_0 = new EnumerationDescriptor.MemberDescriptor("newest_first", "newest_first", 0x7f63219c035cbde0L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9179217419466227168");
  private final EnumerationDescriptor.MemberDescriptor myMember_most_populat_0 = new EnumerationDescriptor.MemberDescriptor("most_populat", "most_populat", 0x7f63219c035cbde1L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9179217419466227169");
  private final EnumerationDescriptor.MemberDescriptor myMember_oldest_first_0 = new EnumerationDescriptor.MemberDescriptor("oldest_first", "oldest_first", 0x7f63219c035cbde2L, "r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/9179217419466227170");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x7f63219c035cbddfL, 0x7f63219c035cbde0L, 0x7f63219c035cbde1L, 0x7f63219c035cbde2L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_newest_first_0, myMember_most_populat_0, myMember_oldest_first_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "newest_first":
        return myMember_newest_first_0;
      case "most_populat":
        return myMember_most_populat_0;
      case "oldest_first":
        return myMember_oldest_first_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
