package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Api = 0;
  public static final int BaseUrl = 1;
  public static final int Content = 2;
  public static final int ContentSource = 3;
  public static final int Contents = 4;
  public static final int Enable = 5;
  public static final int EnableComponents = 6;
  public static final int Endpoint = 7;
  public static final int Endpoints = 8;
  public static final int Favorite = 9;
  public static final int ForEach = 10;
  public static final int ImageLayout = 11;
  public static final int Images = 12;
  public static final int ItemsPerPage = 13;
  public static final int Like = 14;
  public static final int LoadAction = 15;
  public static final int LoadElement = 16;
  public static final int Menu = 17;
  public static final int MenuOption = 18;
  public static final int MenuOptionElement = 19;
  public static final int MenuType = 20;
  public static final int Parameter = 21;
  public static final int Position = 22;
  public static final int Set = 23;
  public static final int Sorting = 24;
  public static final int Style = 25;
  public static final int StyleElement = 26;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL);
    builder.put(0x4b61efe7ede3967eL, Api);
    builder.put(0x4b61efe7ede39682L, BaseUrl);
    builder.put(0x7f63219c035cbe27L, Content);
    builder.put(0x7f63219c035a8ce8L, ContentSource);
    builder.put(0x7f63219c035a8ce2L, Contents);
    builder.put(0x7f63219c035cbe07L, Enable);
    builder.put(0x7f63219c035cbedcL, EnableComponents);
    builder.put(0x4b61efe7ede396a1L, Endpoint);
    builder.put(0x4b61efe7ede396abL, Endpoints);
    builder.put(0x7f63219c035cbee1L, Favorite);
    builder.put(0x7f63219c035cbd05L, ForEach);
    builder.put(0x7f63219c035cbd99L, ImageLayout);
    builder.put(0x7f63219c035cbd8dL, Images);
    builder.put(0x7f63219c035cbdbeL, ItemsPerPage);
    builder.put(0x7f63219c035cbe71L, Like);
    builder.put(0x7f63219c035cbd35L, LoadAction);
    builder.put(0x7f63219c035a8d0eL, LoadElement);
    builder.put(0x5f82ea2efca8b118L, Menu);
    builder.put(0x5f82ea2efca8b121L, MenuOption);
    builder.put(0x5f82ea2efcb389d0L, MenuOptionElement);
    builder.put(0x5f82ea2efcb9e2a7L, MenuType);
    builder.put(0x4b61efe7ede396a7L, Parameter);
    builder.put(0x7f63219c035cbe49L, Position);
    builder.put(0x4b61efe7ede0c75aL, Set);
    builder.put(0x7f63219c035cbddeL, Sorting);
    builder.put(0x5f82ea2efca8b139L, Style);
    builder.put(0x5f82ea2efca8b13bL, StyleElement);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
