package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Login = 0;
  public static final int Menu = 1;
  public static final int MenuOption = 2;
  public static final int MenuOptionElement = 3;
  public static final int MenuType = 4;
  public static final int Style = 5;
  public static final int StyleElement = 6;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL);
    builder.put(0x5f82ea2efcbadc16L, Login);
    builder.put(0x5f82ea2efca8b118L, Menu);
    builder.put(0x5f82ea2efca8b121L, MenuOption);
    builder.put(0x5f82ea2efcb389d0L, MenuOptionElement);
    builder.put(0x5f82ea2efcb9e2a7L, MenuType);
    builder.put(0x5f82ea2efca8b139L, Style);
    builder.put(0x5f82ea2efca8b13bL, StyleElement);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
