package Ryce.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptLogin = createDescriptorForLogin();
  /*package*/ final ConceptDescriptor myConceptMenu = createDescriptorForMenu();
  /*package*/ final ConceptDescriptor myConceptMenuOption = createDescriptorForMenuOption();
  /*package*/ final ConceptDescriptor myConceptMenuOptionElement = createDescriptorForMenuOptionElement();
  /*package*/ final ConceptDescriptor myConceptMenuType = createDescriptorForMenuType();
  /*package*/ final ConceptDescriptor myConceptStyle = createDescriptorForStyle();
  /*package*/ final ConceptDescriptor myConceptStyleElement = createDescriptorForStyleElement();
  /*package*/ final EnumerationDescriptor myEnumerationMenuTypes = new EnumerationDescriptor_MenuTypes();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptLogin, myConceptMenu, myConceptMenuOption, myConceptMenuOptionElement, myConceptMenuType, myConceptStyle, myConceptStyleElement);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Login:
        return myConceptLogin;
      case LanguageConceptSwitch.Menu:
        return myConceptMenu;
      case LanguageConceptSwitch.MenuOption:
        return myConceptMenuOption;
      case LanguageConceptSwitch.MenuOptionElement:
        return myConceptMenuOptionElement;
      case LanguageConceptSwitch.MenuType:
        return myConceptMenuType;
      case LanguageConceptSwitch.Style:
        return myConceptStyle;
      case LanguageConceptSwitch.StyleElement:
        return myConceptStyleElement;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationMenuTypes);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForLogin() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "Login", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcbadc16L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668105038870");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenu() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "Menu", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b118L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668103848216");
    b.version(3);
    b.aggregate("options", 0x5f82ea2efca8b125L).target(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b121L).optional(false).ordered(true).multiple(false).origin("6882320668103848229").done();
    b.aggregate("style", 0x5f82ea2efca9754dL).target(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b139L).optional(true).ordered(true).multiple(false).origin("6882320668103898445").done();
    b.aggregate("type", 0x5f82ea2efcb9e2c4L).target(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb9e2a7L).optional(false).ordered(true).multiple(false).origin("6882320668104975044").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenuOption() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "MenuOption", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b121L);
    b.class_(false, false, false);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668103848225");
    b.version(3);
    b.aggregate("options", 0x5f82ea2efcb389d7L).target(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb389d0L).optional(true).ordered(true).multiple(true).origin("6882320668104559063").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenuOptionElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "MenuOptionElement", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb389d0L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668104559056");
    b.version(3);
    b.property("url", 0x5f82ea2efcb389d2L).type(PrimitiveTypeId.STRING).origin("6882320668104559058").done();
    b.property("text", 0x5f82ea2efcb389d3L).type(PrimitiveTypeId.STRING).origin("6882320668104559059").done();
    b.aggregate("style", 0x5f82ea2efcb389d4L).target(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b139L).optional(true).ordered(true).multiple(false).origin("6882320668104559060").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMenuType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "MenuType", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb9e2a7L);
    b.class_(false, false, false);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668104975015");
    b.version(3);
    b.property("menutype", 0x5f82ea2efcb9e2a8L).type(MetaIdFactory.dataTypeId(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efcb96886L)).origin("6882320668104975016").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStyle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "Style", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b139L);
    b.class_(false, false, true);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668103848249");
    b.version(3);
    b.property("name", 0x5f82ea2efcaaf79eL).type(PrimitiveTypeId.STRING).origin("6882320668103997342").done();
    b.aggregate("CSSproperties", 0x5f82ea2efca8b143L).target(0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b13bL).optional(true).ordered(true).multiple(true).origin("6882320668103848259").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStyleElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Ryce", "StyleElement", 0x5566a3bc3a3d48e5L, 0x9986b96a01ec7badL, 0x5f82ea2efca8b13bL);
    b.class_(false, false, false);
    b.origin("r:6f21ea0b-8f9f-4069-8bcc-6c3e23fc8fea(Ryce.structure)/6882320668103848251");
    b.version(3);
    b.property("name", 0x5f82ea2efca8b14dL).type(PrimitiveTypeId.STRING).origin("6882320668103848269").done();
    b.property("value", 0x5f82ea2efca8b14eL).type(PrimitiveTypeId.STRING).origin("6882320668103848270").done();
    return b.create();
  }
}
